import type { Product } from "./schema";

export const products: Product[] = [
  // Injectable Steroids (MEDINA)
  {
    id: "gh-endogenic",
    name: "GH Endogenic",
    chemicalName: "Somatotropina (HGH)",
    category: "injectable-steroids",
    brand: "MEDINA",
    concentration: "100 IU",
    quantity: "10×10 IU",
    priceEur: 222.05,
<<<<<<< HEAD
=======
    image: "/attached_assets/Bez tytułu_1762047957578.png",
    description: "GH Endogenic is recombinant menselijk groeihormoon (HGH) van farmaceutische kwaliteit. Het bevordert spiergroei, vetverbranding en herstel.",
    usage: "Subcutane of intramusculaire injectie, dagelijks of meerdere keren per dag",
    dosage: "2-4 IU per dag voor anti-aging en herstel, 4-8 IU per dag voor bodybuilding doeleinden",
    benefits: [
      "Verbeterde vetverlies bij behoud van spiermassa",
      "Verhoogde spiergroei en recuperatie",
      "Verbeterde huidkwaliteit en anti-aging effecten",
      "Sterkere botten en gewrichten",
      "Verbeterde slaapkwaliteit",
      "Toegenomen energieniveaus"
    ],
    warnings: [
      "Medisch toezicht sterk aanbevolen",
      "Kan bloedsuikerspiegel beïnvloeden",
      "Niet gebruiken bij kanker of tumoren",
      "Langdurig gebruik vereist monitoring",
      "Bewaar gekoeld tussen 2-8°C"
    ],
    ingredients: "Somatropine (recombinant HGH) 10 IU per flacon, mannitol, natriumfosfaat buffer"
>>>>>>> 34a4f782f312307699de96b76e2c43780e1deb25
  },
  {
    id: "test-enan",
    name: "Test Enan",
    chemicalName: "Testosteron Enanthate",
    category: "injectable-steroids",
    brand: "MEDINA",
    concentration: "300 mg/ml",
    quantity: "10 ml",
    priceEur: 34.16,
<<<<<<< HEAD
=======
    image: "/attached_assets/image_1762051320696.png",
    description: "Test Enan (Testosteron Enanthate) is een langwerkend testosteron ester dat wordt gebruikt voor spiergroei en kracht. Het is een van de meest populaire anabole steroïden voor massa-opbouw.",
    usage: "Intramusculaire injectie, meestal 1-2 keer per week",
    dosage: "Typisch 300-600 mg per week voor gevorderde gebruikers. Beginners starten vaak met 300 mg per week.",
    benefits: [
      "Significante toename in spiermassa",
      "Verhoogde kracht en power output",
      "Verbeterd herstel na training",
      "Verhoogde eiwitynthese",
      "Verbeterde stikstofretentie"
    ],
    warnings: [
      "Alleen voor volwassenen boven 21 jaar",
      "Medisch toezicht vereist",
      "Kan bijwerkingen veroorzaken zoals aromatisatie",
      "Niet aanbevolen voor vrouwen",
      "Post Cycle Therapy (PCT) is noodzakelijk"
    ],
    ingredients: "Testosteron Enanthate 300mg/ml, Benzyl Alcohol, Benzyl Benzoate, Druivenpitolie"
>>>>>>> 34a4f782f312307699de96b76e2c43780e1deb25
  },
  {
    id: "test-cypio",
    name: "Test Cypio",
    chemicalName: "Testosteron Cypionate",
    category: "injectable-steroids",
    brand: "MEDINA",
    concentration: "300 mg/ml",
    quantity: "10 ml",
    priceEur: 34.16,
  },
  {
    id: "test-susta",
    name: "Test Susta",
    chemicalName: "Testosteron mix (Sustanon 300)",
    category: "injectable-steroids",
    brand: "MEDINA",
    concentration: "300 mg/ml",
    quantity: "10 ml",
    priceEur: 34.16,
  },
  {
    id: "test-prop",
    name: "Test Prop",
    chemicalName: "Testosteron Propionate",
    category: "injectable-steroids",
    brand: "MEDINA",
    concentration: "100 mg/ml",
    quantity: "10 ml",
    priceEur: 30.74,
  },
  {
    id: "dekanian",
    name: "Dekanian",
    chemicalName: "Nandrolone Decanoate",
    category: "injectable-steroids",
    brand: "MEDINA",
    concentration: "400 mg/ml",
    quantity: "10 ml",
    priceEur: 40.99,
  },
  {
    id: "tritest",
    name: "Tritest",
    chemicalName: "Testosteron blend (E/C/P)",
    category: "injectable-steroids",
    brand: "MEDINA",
    concentration: "450 mg/ml",
    quantity: "10 ml",
    priceEur: 40.99,
  },
  {
    id: "boldenon",
    name: "Boldenon",
    chemicalName: "Boldenone Undecylenate",
    category: "injectable-steroids",
    brand: "MEDINA",
    concentration: "300 mg/ml",
    quantity: "10 ml",
    priceEur: 40.99,
  },
  {
    id: "deka",
    name: "Deka",
    chemicalName: "Nandrolone Decanoate",
    category: "injectable-steroids",
    brand: "MEDINA",
    concentration: "300 mg/ml",
    quantity: "10 ml",
    priceEur: 40.99,
  },
  {
    id: "npp",
    name: "NPP",
    chemicalName: "Nandrolone Phenylpropionate",
    category: "injectable-steroids",
    brand: "MEDINA",
    concentration: "100 mg/ml",
    quantity: "10 ml",
    priceEur: 37.59,
  },
  {
    id: "masteron-p",
    name: "Masteron P",
    chemicalName: "Drostanolone Propionate",
    category: "injectable-steroids",
    brand: "MEDINA",
    concentration: "100 mg/ml",
    quantity: "10 ml",
    priceEur: 44.42,
  },
  {
    id: "masteron-e",
    name: "Masteron E",
    chemicalName: "Drostanolone Enanthate",
    category: "injectable-steroids",
    brand: "MEDINA",
    concentration: "200 mg/ml",
    quantity: "10 ml",
    priceEur: 51.24,
  },
  {
    id: "tren-a",
    name: "Tren A",
    chemicalName: "Trenbolone Acetate",
    category: "injectable-steroids",
    brand: "MEDINA",
    concentration: "100 mg/ml",
    quantity: "10 ml",
    priceEur: 44.42,
<<<<<<< HEAD
=======
    image: "/attached_assets/image_1762051320696.png",
    description: "Trenbolone Acetate is een van de krachtigste anabole steroïden beschikbaar. Het staat bekend om zijn vermogen om spiermassa en kracht dramatisch te verhogen.",
    usage: "Intramusculaire injectie, om de dag of dagelijks vanwege korte halfwaardetijd",
    dosage: "50-100 mg om de dag voor gevorderde gebruikers. Niet aanbevolen voor beginners.",
    benefits: [
      "Extreme toename in spiermassa en dichtheid",
      "Dramatische verhoging van kracht",
      "Geen aromatisatie naar oestrogeen",
      "Verhoogde vetverlies tijdens massa-opbouw",
      "Verbeterde vascularity en hardheid"
    ],
    warnings: [
      "Alleen voor zeer ervaren gebruikers",
      "Kan cardiovasculaire bijwerkingen veroorzaken",
      "Mogelijk nachtelijk zweten en slapeloosheid",
      "Sterk androgeen - niet voor vrouwen",
      "Medisch toezicht sterk aanbevolen"
    ],
    ingredients: "Trenbolone Acetate 100mg/ml, Benzyl Alcohol, Benzyl Benzoate, Druivenpitolie"
>>>>>>> 34a4f782f312307699de96b76e2c43780e1deb25
  },
  {
    id: "tren-e",
    name: "Tren E",
    chemicalName: "Trenbolone Enanthate",
    category: "injectable-steroids",
    brand: "MEDINA",
    concentration: "200 mg/ml",
    quantity: "10 ml",
    priceEur: 47.82,
  },
  {
    id: "tren-hexa",
    name: "Tren Hexa",
    chemicalName: "Trenbolone Hexahydrobenzylcarbonate",
    category: "injectable-steroids",
    brand: "MEDINA",
    concentration: "100 mg/ml",
    quantity: "10 ml",
    priceEur: 61.50,
  },
  {
    id: "dhb",
    name: "DHB",
    chemicalName: "1-Testosterone Cypionate",
    category: "injectable-steroids",
    brand: "MEDINA",
    concentration: "100 mg/ml",
    quantity: "10 ml",
    priceEur: 47.82,
  },
  {
    id: "ment",
    name: "MENT",
    chemicalName: "Trestolone Acetate",
    category: "injectable-steroids",
    brand: "MEDINA",
    concentration: "50 mg/ml",
    quantity: "10 ml",
    priceEur: 61.50,
  },
  {
    id: "primabolan",
    name: "Primabolan",
    chemicalName: "Methenolone Enanthate",
    category: "injectable-steroids",
    brand: "MEDINA",
    concentration: "100 mg/ml",
    quantity: "10 ml",
    priceEur: 64.91,
  },
  {
    id: "meta-inj",
    name: "Meta Inj",
    chemicalName: "Methandienone (injecteerbaar)",
    category: "injectable-steroids",
    brand: "MEDINA",
    concentration: "50 mg/ml",
    quantity: "10 ml",
    priceEur: 37.59,
  },
  {
    id: "anapolon-inj",
    name: "Anapolon Inj",
    chemicalName: "Oxymetholone (injecteerbaar)",
    category: "injectable-steroids",
    brand: "MEDINA",
    concentration: "50 mg/ml",
    quantity: "10 ml",
    priceEur: 37.59,
  },
  {
    id: "winstrol-inj",
    name: "Winstrol Inj",
    chemicalName: "Stanozolol (injecteerbaar)",
    category: "injectable-steroids",
    brand: "MEDINA",
    concentration: "50 mg/ml",
    quantity: "10 ml",
    priceEur: 37.59,
  },
  // HCG
  {
    id: "hcg-endogenic",
    name: "HCG Endogenic",
    chemicalName: "Chorionic Gonadotropin",
    category: "hcg",
    brand: "ENDOGENIC",
    quantity: "5000 IU",
    priceEur: 37.59,
<<<<<<< HEAD
=======
    image: "/attached_assets/Endogenic peptydy_1762048163392.png",
    description: "HCG (Human Chorionic Gonadotropin) wordt gebruikt om de natuurlijke testosteronproductie te stimuleren, vooral belangrijk tijdens en na steroïde cycli.",
    usage: "Subcutane of intramusculaire injectie, 2-3 keer per week",
    dosage: "250-500 IU, 2-3 keer per week tijdens cyclus. 1000-1500 IU om de dag voor PCT.",
    benefits: [
      "Stimuleert natuurlijke testosteronproductie",
      "Voorkomt testikel atrofie tijdens cyclus",
      "Ondersteunt vruchtbaarheid",
      "Helpt LH en FSH niveaus te herstellen",
      "Essentieel voor effectieve Post Cycle Therapy"
    ],
    warnings: [
      "Niet te veel of te vaak gebruiken",
      "Kan oestrogeen verhogen - monitor dit",
      "Bewaar in koelkast na reconstitutie",
      "Gebruik binnen 60 dagen na reconstitutie",
      "Medisch advies aanbevolen"
    ],
    ingredients: "HCG 5000 IU, mannitol, natriumfosfaat buffer, steriel water (apart verpakt)"
>>>>>>> 34a4f782f312307699de96b76e2c43780e1deb25
  },
  {
    id: "hcg-pregnyl",
    name: "HCG Pregnyl",
    chemicalName: "Chorionic Gonadotropin (Pregnyl®)",
    category: "hcg",
    brand: "MEDINA",
    quantity: "5000 IU",
    priceEur: 27.33,
  },
  {
    id: "hcg-magnus",
    name: "HCG Magnus",
    chemicalName: "Chorionic Gonadotropin (Magnus)",
    category: "hcg",
    brand: "MEDINA",
    quantity: "5000 IU",
    priceEur: 27.33,
  },
  {
    id: "hcg-polfa",
    name: "HCG Polfa",
    chemicalName: "Chorionic Gonadotropin (Polfa)",
    category: "hcg",
    brand: "MEDINA",
    quantity: "5000 IU",
    priceEur: 40.99,
  },
  // Oral Tablets & SARMs
  {
    id: "meta",
    name: "Meta",
    chemicalName: "Methandienone (Dianabol)",
    category: "oral-sarms",
    brand: "MEDINA",
    concentration: "10 mg/tab",
    quantity: "100 tabletten",
    priceEur: 30.74,
<<<<<<< HEAD
=======
    image: "/attached_assets/image_1762051320696.png",
    description: "Methandienone, ook bekend als Dianabol, is een van de populairste orale anabole steroïden voor snelle massa-opbouw en krachttoename.",
    usage: "Oraal, met voedsel innemen voor betere maagvertraging",
    dosage: "20-50 mg per dag, verdeeld over meerdere doses. Cyclus van 4-6 weken.",
    benefits: [
      "Snelle toename in spiermassa",
      "Verhoogde kracht binnen enkele dagen",
      "Verbeterde stikstofretentie",
      "Verhoogde eiwitynthese",
      "Verbeterd herstel"
    ],
    warnings: [
      "Levertoxisch - gebruik leverondersteuning",
      "Aromatiseert naar oestrogeen",
      "Kan vochtretentie veroorzaken",
      "Niet langer dan 6 weken gebruiken",
      "Post Cycle Therapy noodzakelijk"
    ],
    ingredients: "Methandienone 10mg per tablet, microkristallijne cellulose, magnesiumstearaat"
>>>>>>> 34a4f782f312307699de96b76e2c43780e1deb25
  },
  {
    id: "winstrol",
    name: "Winstrol",
    chemicalName: "Stanozolol",
    category: "oral-sarms",
    brand: "MEDINA",
    concentration: "10 mg/tab",
    quantity: "100 tabletten",
    priceEur: 34.16,
  },
  {
    id: "tura",
    name: "Tura",
    chemicalName: "Turinabol",
    category: "oral-sarms",
    brand: "MEDINA",
    concentration: "10 mg/tab",
    quantity: "100 tabletten",
    priceEur: 40.99,
  },
  {
    id: "oxa",
    name: "Oxa",
    chemicalName: "Oxandrolone",
    category: "oral-sarms",
    brand: "MEDINA",
    concentration: "10 mg/tab",
    quantity: "100 tabletten",
    priceEur: 61.50,
  },
  {
    id: "anapolon",
    name: "Anapolon",
    chemicalName: "Oxymetholone",
    category: "oral-sarms",
    brand: "MEDINA",
    concentration: "50 mg/tab",
    quantity: "100 tabletten",
    priceEur: 58.07,
  },
  {
    id: "yohimbina",
    name: "Yohimbina",
    chemicalName: "Yohimbine HCl",
    category: "oral-sarms",
    brand: "MEDINA",
    concentration: "10 mg/tab",
    quantity: "100 tabletten",
    priceEur: 37.59,
  },
  {
    id: "sr9011",
    name: "SR9011",
    chemicalName: "SR9011 (Rev-ErbA Agonist)",
    category: "oral-sarms",
    brand: "MEDINA",
    concentration: "5 mg/tab",
    quantity: "100 tabletten",
    priceEur: 47.82,
  },
  {
    id: "gw",
    name: "GW",
    chemicalName: "GW501516 (Cardarine)",
    category: "oral-sarms",
    brand: "MEDINA",
    concentration: "10 mg/tab",
    quantity: "100 tabletten",
    priceEur: 51.24,
  },
  {
    id: "mk677",
    name: "MK677",
    chemicalName: "Ibutamoren (MK-677)",
    category: "oral-sarms",
    brand: "MEDINA",
    concentration: "10 mg/tab",
    quantity: "100 tabletten",
    priceEur: 54.66,
  },
  {
    id: "ostarina",
    name: "Ostarina",
    chemicalName: "Ostarine (MK-2866)",
    category: "oral-sarms",
    brand: "MEDINA",
    concentration: "10 mg/tab",
    quantity: "100 tabletten",
    priceEur: 44.42,
  },
  {
    id: "sr9009",
    name: "SR9009",
    chemicalName: "SR9009 (Stenabolic)",
    category: "oral-sarms",
    brand: "MEDINA",
    concentration: "10 mg/tab",
    quantity: "100 tabletten",
    priceEur: 61.50,
  },
  // Peptides (ENDOGENIC)
  {
    id: "bpc-157",
    name: "BPC 157",
    chemicalName: "Body Protection Compound-157",
    category: "peptides",
    brand: "ENDOGENIC",
    quantity: "5 mg",
    priceEur: 37.59,
<<<<<<< HEAD
=======
    image: "/attached_assets/Endogenic peptydy_1762048163392.png",
    description: "BPC-157 is een synthetisch peptide dat bestaat uit 15 aminozuren. Het is afgeleid van een beschermend maageiwit en staat bekend om zijn helende eigenschappen.",
    usage: "Subcutane of intramusculaire injectie, bij voorkeur nabij het te behandelen gebied",
    dosage: "200-500 mcg per dag, verdeeld over 1-2 injecties. Cyclus van 4-6 weken",
    benefits: [
      "Versneld herstel van pezen en ligamenten",
      "Bevordert wondgenezing",
      "Anti-inflammatoire eigenschappen",
      "Beschermt en geneest het maag-darmstelsel",
      "Ondersteunt vasculaire gezondheid",
      "Kan helpen bij gewrichtspijn"
    ],
    warnings: [
      "Alleen voor onderzoeksdoeleinden",
      "Raadpleeg een arts voor therapeutisch gebruik",
      "Bewaar in koelkast na reconstitutie",
      "Gebruik steriel water voor reconstitutie",
      "Niet geschikt tijdens zwangerschap"
    ],
    ingredients: "BPC-157 peptide 5mg, mannitol als stabilisator"
>>>>>>> 34a4f782f312307699de96b76e2c43780e1deb25
  },
  {
    id: "epithalon",
    name: "Epithalon",
    chemicalName: "Epitalon (Epithalamin)",
    category: "peptides",
    brand: "ENDOGENIC",
    quantity: "10 mg",
    priceEur: 37.59,
  },
  {
    id: "ghk-cu",
    name: "GHK-Cu",
    chemicalName: "Copper Peptide GHK-Cu",
    category: "peptides",
    brand: "ENDOGENIC",
    quantity: "50 mg",
    priceEur: 37.59,
  },
  {
    id: "kisspeptin",
    name: "Kisspeptin",
    chemicalName: "Kisspeptin-10",
    category: "peptides",
    brand: "ENDOGENIC",
    quantity: "5 mg",
    priceEur: 37.59,
  },
  {
    id: "ghrp-2",
    name: "GHRP-2",
    chemicalName: "Growth Hormone Releasing Peptide-2",
    category: "peptides",
    brand: "ENDOGENIC",
    quantity: "5 mg",
    priceEur: 37.59,
  },
  {
    id: "ghrp-6",
    name: "GHRP-6",
    chemicalName: "Growth Hormone Releasing Peptide-6",
    category: "peptides",
    brand: "ENDOGENIC",
    quantity: "5 mg",
    priceEur: 37.59,
  },
  {
    id: "fragment",
    name: "Fragment",
    chemicalName: "GH Fragment 176-191",
    category: "peptides",
    brand: "ENDOGENIC",
    quantity: "5 mg",
    priceEur: 40.99,
  },
  {
    id: "melanotan-ii",
    name: "Melanotan II",
    chemicalName: "Melanotan II",
    category: "peptides",
    brand: "ENDOGENIC",
    quantity: "10 mg",
    priceEur: 37.59,
  },
  {
    id: "selank",
    name: "Selank",
    chemicalName: "Selank Peptide",
    category: "peptides",
    brand: "ENDOGENIC",
    quantity: "5 mg",
    priceEur: 37.59,
  },
  {
    id: "semax",
    name: "Semax",
    chemicalName: "Semax Peptide",
    category: "peptides",
    brand: "ENDOGENIC",
    quantity: "5 mg",
    priceEur: 58.07,
  },
  {
    id: "tb-500",
    name: "TB-500",
    chemicalName: "Thymosin Beta-4",
    category: "peptides",
    brand: "ENDOGENIC",
    quantity: "5 mg",
    priceEur: 37.59,
  },
  {
    id: "cjc-bez-dac",
    name: "CJC bez DAC",
    chemicalName: "CJC-1295 zonder DAC",
    category: "peptides",
    brand: "ENDOGENIC",
    quantity: "5 mg",
    priceEur: 37.59,
  },
  {
    id: "cjc-z-dac",
    name: "CJC z DAC",
    chemicalName: "CJC-1295 met DAC",
    category: "peptides",
    brand: "ENDOGENIC",
    quantity: "5 mg",
    priceEur: 40.99,
  },
  {
    id: "pt-141",
    name: "PT-141",
    chemicalName: "Bremelanotide (PT-141)",
    category: "peptides",
    brand: "ENDOGENIC",
    quantity: "10 mg",
    priceEur: 51.24,
  },
  {
    id: "peg-mgf",
    name: "PEG-MGF",
    chemicalName: "PEGylated Mechano Growth Factor",
    category: "peptides",
    brand: "ENDOGENIC",
    quantity: "5 mg",
    priceEur: 51.24,
  },
  {
    id: "oksytocyna",
    name: "Oksytocyna",
    chemicalName: "Oxytocin",
    category: "peptides",
    brand: "ENDOGENIC",
    quantity: "5 mg",
    priceEur: 37.59,
  },
  {
    id: "dsip",
    name: "DSIP",
    chemicalName: "Delta Sleep-Inducing Peptide",
    category: "peptides",
    brand: "ENDOGENIC",
    quantity: "5 mg",
    priceEur: 40.99,
  },
  {
    id: "ipamorelin",
    name: "Ipamorelin",
    chemicalName: "Ipamorelin",
    category: "peptides",
    brand: "ENDOGENIC",
    quantity: "5 mg",
    priceEur: 37.59,
  },
  {
    id: "thymosin-alpha",
    name: "Thymosin Alpha",
    chemicalName: "Thymosin Alpha-1",
    category: "peptides",
    brand: "ENDOGENIC",
    quantity: "5 mg",
    priceEur: 88.83,
  },
  {
    id: "adamax",
    name: "Adamax",
    chemicalName: "Adipotide (FTPP)",
    category: "peptides",
    brand: "ENDOGENIC",
    quantity: "5 mg",
    priceEur: 64.91,
  },
  {
    id: "cortagen",
    name: "Cortagen",
    chemicalName: "Cortagen Peptide",
    category: "peptides",
    brand: "ENDOGENIC",
    quantity: "5 mg",
    priceEur: 64.91,
  },
  {
    id: "igf-1-oxymedin",
    name: "IGF-1 Oxymedin",
    chemicalName: "Insulin-like Growth Factor-1",
    category: "peptides",
    brand: "ENDOGENIC",
    quantity: "1 mg",
    priceEur: 290.38,
  },
];

export const categoryNames: Record<string, string> = {
  "injectable-steroids": "Injecteerbare Steroïden",
  "hcg": "HCG & Gonadotropinen",
  "oral-sarms": "Tabletten & SARMs",
  "peptides": "Peptiden & Hormonen",
};

export const categoryIcons: Record<string, string> = {
  "injectable-steroids": "💉",
  "hcg": "🧪",
  "oral-sarms": "💊",
  "peptides": "🧬",
};
